sudo: false
language: ruby
rvm: 2.5.1
services: postgresql
bundler_args: "--without development --deployment -j4"
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
script: bundle exec rails test
